language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.6.1 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

after_success:
  - cd tests; composer install --no-interaction; cd ../;
  - travis_retry php tests/vendor/bin/coveralls  -c ./.coveralls.yml
  # or enable logging
  - travis_retry php tests/vendor/bin/coveralls  -c ./.coveralls.yml -v
